# Generated by Django 3.1 on 2020-11-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('jugadores', models.ManyToManyField(blank=True, related_name='jugadores', to='app.Jugador')),
            ],
        ),
    ]
