# Generated by Django 3.1 on 2020-11-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_club_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='jugadores',
        ),
        migrations.AddField(
            model_name='jugador',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='app.club'),
        ),
    ]
