# Generated by Django 3.1 on 2020-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201119_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='club',
            name='pais',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='club',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
