# Generated by Django 3.1 on 2020-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201126_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='dinero_ganado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='club',
            name='dinero_invertido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
