# Generated by Django 3.1.4 on 2020-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201203_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
